<?php

define('CURRENT_DATE', date('Y-m-d'));

define('CACHE_STORAGE_MEMCACHE', 1);
define('CACHE_STORAGE_MEMCACHED', 2);
defined('CACHE_STORAGE_DEFAULT') or define('CACHE_STORAGE_DEFAULT', CACHE_STORAGE_MEMCACHED);

defined('FIXTURES_LIMIT_COEF') or define('FIXTURES_LIMIT_COEF', 50);

define('CLI_CARRIAGE_RETURN', "\r\e[0K");
